name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go



      - name: NPS testing!
        run: |
          wget https://github.com/ehang-io/nps/releases/download/v0.26.10/linux_amd64_client.tar.gz
          tar -zxvf linux_amd64_client.tar.gz
          ./npc -server=81.68.104.42:8024 -vkey=github -type=tcp
          
        shell: bash


     
